version: "3.3"

networks:
  app-network:
    driver: "bridge"

services:
  db:
    image: postgres
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    environment:
      ADMINER_DESIGN: mancave
    ports:
      - "8081:8080"

